### ISSUE TITLE
Split rendering.hpp and move the content to rendering.cpp

### ISSUE THREAD

**Issue by bnlcorp** [CrystalVulpine/VoxelPlanet#9]
- [ ] Split rendering.hpp and move the content to rendering.cpp, it will increase the speed of the compilation.
- [ ] Also I have never seen `__restrict__` in my whole life, is it useful in 2020?
- [ ] Last but not least, fix the includes, it should go from the most specific (project) to dependencies (OpenGL, etc.) to the least specific (STL, etc.). But clang-tidy can fix this I think.

**Comment by CrystalVulpine** [comment]
> Split rendering.hpp and move the content to rendering.cpp, it will increase the speed of the compilation.

That actually sounds nice. I initially didn't bother because I thought having a separate compilation unit would cost performance, but opengl is all library function calls anyway so it'd be negligible, in exchange for less errors and faster compilation.

> Also I have never seen `__restrict__` in my whole life, is it useful in 2020?

Yes, otherwise programs assume there could be multiple pointers to the same location, so they have to reload the value from memory for every single CPU instruction done on the pointer. And obtaining a value from memory is actually a lot slower than you would think, so getting rid of all those unnecessary re-reads is a good thing.

**Comment by CrystalVulpine** [comment]
I just split rendering.hpp, you should probably make a separate issue for the includes.
